# Docker
# Build and push an image to DockerHub
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
variables:
- name: "app-name"
  value: "dotnet-app01-deployment"
- group: "dotnetapp"
    
trigger:
- main
- master
- develop
- release
- release/*
- feature/*
- features/*

resources:
- repo: self

stages:
- stage: GitClone
  displayName: Clonning Repo
  jobs:
  - job: Git
    displayName: Clonning Repo $(dotnet-app01-deploymen)
    pool:
      name: bradoquy-k8s
    steps:
    - task: CmdLine@2
      displayName: Clonning Repo $(dotnet-app01-deploymen)
      inputs:
        script: |
          'rm -rf bradoquy-docker-app'
          'git clone https://github.com/oliveiha/bradoquy-docker-app.git'
- stage: ListDir
  displayName: Listing Directory
  jobs:
  - job: ls
    displayName: Listing Directory
    pool:
      name: bradoquy-k8s
    steps:
    - task: CmdLine@2
      displayName: Pwd on Directory
      inputs:
        script: 'pwd'
    - task: CmdLine@2
      displayName: List Directory
      inputs:
        script: 'ls -la docker-app/'
- stage: Build 
  displayName: Build dotnet app
  jobs:
  - job: DockerBuild
    displayName: Build
    pool:
      name: bradoquy-k8s
    steps:
    - task: Docker@2
      displayName: Docker build dotnet app
      inputs:
        containerRegistry: 'oliveiha-dockerhub'
        repository: 'oliveiha/dotnetapp'
        command: 'build'
        Dockerfile: 'docker-app/docker-app/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
- stage: DockerPush 
  displayName: push dotnet app
  jobs:
  - job: Push
    displayName: Push dotnet app
    pool:
      name: bradoquy-k8s
    steps:        
    - task: Docker@2
      displayName: Docker push dotnet app
      inputs:
        containerRegistry: 'oliveiha-dockerhub'
        repository: 'oliveiha/dotnetapp'
        command: 'push'
        tags: |
          latest
          $(Build.BuildId)
- stage: ConfigKubectl 
  displayName: Config kubectl 
  jobs:
  - job: ConfigKubectl
    displayName: Install kubectl
    pool:
      name: bradoquy-k8s
    steps:        
    - task: CmdLine@2
      displayName: Download kubectl  
      inputs:
        script: 'curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"'
    - task: CmdLine@2
      displayName: Install kubectl
      inputs:
        script: 'install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl'
    - task: CopyFiles@1
      displayName: Copy Minikube Files
      inputs:
        SourceFolder: './k8s-manifests/'
        Contents: |
          minikube
        TargetFolder: '$(Build.ArtifactStagingDirectory)' 
    - task: CopyFiles@1
      displayName: Copy kubectl config File
      inputs:
        SourceFolder: './k8s-manifests/'
        Contents: |
          config
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: CmdLine@2
      displayName: Copy minikube and config to root dir
      inputs:
        script: 'cp -r /azp/_work/1/s/k8s-manifests/minikube/ /root/ && cp -r /azp/_work/1/s/k8s-manifests/config /root/.kube/'    
    - task: CmdLine@2
      displayName: Testing Kubectl
      inputs:
        script: 'kubectl get nodes'             
- stage: CopyK8sManifests 
  displayName: Copy kubernetes manifests 
  jobs:
  - job: CopyK8sManifests
    displayName: Copy kubernetes manifests 
    pool:
      name: bradoquy-k8s
    steps:        
    - task: CopyFiles@2
      inputs:
        SourceFolder: './k8s-manifests'
        Contents: |
          deployment.yaml
          service.yaml
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

- stage: DeployK8sManifests 
  displayName: Deploy kubernetes manifests 
  jobs:
  - job: DeployK8sManifests
    displayName: Deploy kubernetes manifests 
    pool:
      name: bradoquy-k8s
    steps:   
    - task: CmdLine@2
      displayName: Delete App
      inputs:
        script: 'cd /azp/_work/1/s/k8s-manifests && kubectl delete deployment $(app-name)'
    - task: CmdLine@2
      displayName: Deploy Deployment
      inputs:
        script: 'cd /azp/_work/1/s/k8s-manifests && kubectl apply -f deployment.yaml'
        
    - task: CmdLine@2
      displayName: Deploy Service
      inputs:
        script: 'cd /azp/_work/1/s/k8s-manifests && kubectl apply -f service.yaml'     
          
        
