- task: Docker@2
  displayName: Docker build dotnet app
  pool:
    name: bradoquy-docker
  inputs:
    containerRegistry: 'oliveiha-dockerhub'
    repository: 'oliveiha/dotnetapp'
    command: 'build'
    Dockerfile: '**docker-app/Dockerfile'


- task: Docker@2
  displayName: Docker push dotnet app
  pool:
    name: bradoquy-docker 
  inputs:
    containerRegistry: 'oliveiha-dockerhub'
    repository: 'oliveiha/dotnetapp'
    command: 'push'