# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Docker@2
pool:
  name: bradoquy-docker
  inputs:
    containerRegistry: 'oliveiha-dockerhub'
    repository: 'oliveiha/dotnetapp'
    command: 'buildAndPush'
    Dockerfile: $(Build.SourcesDirectory)/docker-app/Dockerfile'



