# Docker
# Build and push an image to DockerHub
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
 
trigger:
- master
 
resources:
- repo: self
stages:
- stage: Build 
  displayName: Build dotnet app
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: bradoquy-docker
    steps:
    - task: Docker@2
      displayName: Docker build dotnet app
      inputs:
        containerRegistry: 'oliveiha-dockerhub'
        repository: 'oliveiha/dotnetapp'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/docker-app/Dockerfile'
    - task: Docker@2
      displayName: Docker push dotnet app
      inputs:
        containerRegistry: 'oliveiha-dockerhub'
        repository: 'oliveiha/dotnetapp'
        command: 'push'
