apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app01-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app01
  template:
    metadata:
      labels:
        app: dotnet-app01
    spec:
      containers:
      - name: my-image
        image: oliveiha/dotnetapp:94
        ports:
        - containerPort: 80